User.create(name: "Jenny", username: "jennybenny", password: "1234")
User.create(name: "Andrew", username: "andrewasj", password: "1234")
User.create(name: "Steven", username: "stevielameanie", password: "1234")
User.create(name: "Jungkook", username: "jungshook", password: "1234")

Entry.create(user_id: 1, the_entry: "Mattie Silver had lived under Ethan’s roof for a year, and from early morning till they met at supper he had frequent chances of seeing her; but no moments in her company were comparable to those when, her arm in his, and her light step flying to keep time with his long stride, they walked back through the night to the farm. He had taken to the girl from the first day, when he had driven over to the Flats to meet her, and she had smiled and waved to him from the train, crying out, “You must be Ethan!” as she jumped down with her bundles, while he reflected, looking over her slight person: “She don’t look much on housework, but she ain’t a fretter, anyhow.” But it was not only that the coming to his house of a bit of hopeful young life was like the lighting of a fire on a cold hearth. The girl was more than the bright serviceable creature he had thought her. She had an eye to see and an ear to hear: he could show her things and tell her things, and taste the bliss of feeling that all he imparted left long reverberations and echoes he could wake at will.

    It was during their night walks back to the farm that he felt most intensely the sweetness of this communion. He had always been more sensitive than the people about him to the appeal of natural beauty. His unfinished studies had given form to this sensibility and even in his unhappiest moments field and sky spoke to him with a deep and powerful persuasion. But hitherto the emotion had remained in him as a silent ache, veiling with sadness the beauty that evoked it. He did not even know whether any one else in the world felt as he did, or whether he was the sole victim of this mournful privilege. Then he learned that one other spirit had trembled with the same touch of wonder: that at his side, living under his roof and eating his bread, was a creature to whom he could say: “That’s Orion down yonder; the big fellow to the right is Aldebaran, and the bunch of little ones—like bees swarming—they’re the Pleiades...” or whom he could hold entranced before a ledge of granite thrusting up through the fern while he unrolled the huge panorama of the ice age, and the long dim stretches of succeeding time. The fact that admiration for his learning mingled with Mattie’s wonder at what he taught was not the least part of his pleasure. And there were other sensations, less definable but more exquisite, which drew them together with a shock of silent joy: the cold red of sunset behind winter hills, the flight of cloud-flocks over slopes of golden stubble, or the intensely blue shadows of hemlocks on sunlit snow. When she said to him once: “It looks just as if it was painted!” it seemed to Ethan that the art of definition could go no farther, and that words had at last been found to utter his secret soul....
    
    ", mood: "happy", food: "I ate corn on the cob, rice, and drank a mango smoothie in the morning. But I'm still very hungry, so I think I'm going to go to Trader Joe's and buy some chips yay ❤️", gratitude: "I am grateful for the fact that it is a Saturday today. I get to finish my project and stay in.", title: "Today is a Saturday! Yay!", date: "2021-06-09")
Entry.create(user_id: 1, the_entry: "As he stood in the darkness outside the church these memories came back with the poignancy of vanished things. Watching Mattie whirl down the floor from hand to hand he wondered how he could ever have thought that his dull talk interested her. To him, who was never gay but in her presence, her gaiety seemed plain proof of indifference. The face she lifted to her dancers was the same which, when she saw him, always looked like a window that has caught the sunset. He even noticed two or three gestures which, in his fatuity, he had thought she kept for him: a way of throwing her head back when she was amused, as if to taste her laugh before she let it out, and a trick of sinking her lids slowly when anything charmed or moved her.", mood: "sad", food: "Today I was so sad I ate so much food today. I ate a huge gigantic bag of family-size Lays.", gratitude: "I'm grateful that tomorrow is a weekend so I can sleep in and that I'll have time to work out tomorrow as well, especially since I ate so much junk food today...", title: "I ate so much today...", date: "2021-06-10")
Entry.create(user_id: 1, the_entry: "In today’s idea-driven economy, the cost of time is what really matters. With the constant pressure to innovate, it makes little sense to waste countless collective hours commuting. So, the most efficient and productive regions are those in which people are thinking and working—not sitting in traffic.

    The auto-dependent transportation system has reached its limit in most major cities and megaregions. Commuting by car is among the least efficient of all our activities—not to mention among the least enjoyable, according to detailed research by the Nobel Prize–winning economist Daniel Kahneman and his colleagues. Though one might think that the economic crisis beginning in 2007 would have reduced traffic (high unemployment means fewer workers traveling to and from work), the opposite has been true. Average commutes have lengthened, and congestion has gotten worse, if anything. The average commute rose in 2008 to 25.5 minutes, “erasing years of decreases to stand at the level of 2000, as people had to leave home earlier in the morning to pick up friends for their ride to work or to catch a bus or subway train,” according to the U.S. Census Bureau, which collects the figures. And those are average figures. Commutes are far longer in the big West Coast cities of Los Angeles and San Francisco and the East Coast cities of New York, Philadelphia, Baltimore, and Washington, D.C. In many of these cities, gridlock has become the norm, not just at rush hour but all day, every day.", mood: "tired", food: "I was so tired today I ate a lot of sweet stuff, like chocolate and candy. I must be getting my period soon since I'm craving so much sweets haha.", gratitude: "tired", date: "2021-06-11")
Entry.create(user_id: 1, the_entry: "The costs are astounding. In Los Angeles, congestion eats up more than 485 million working hours a year; that’s seventy hours, or nearly two weeks, of full-time work per commuter. In D.C., the time cost of congestion is sixty-two hours per worker per year. In New York it’s forty-four hours. Average it out, and the time cost across America’s thirteen biggest city-regions is fifty-one hours per worker per year. Across the country, commuting wastes 4.2 billion hours of work time annually—nearly a full workweek for every commuter. The overall cost to the U.S. economy is nearly $90 billion when lost productivity and wasted fuel are taken into account. At the Martin Prosperity Institute, we calculate that every minute shaved off America’s commuting time is worth $19.5 billion in value added to the economy. The numbers add up fast: five minutes is worth $97.7 billion; ten minutes, $195 billion; fifteen minutes, $292 billion.

    It’s ironic that so many people still believe the main remedy for traffic congestion is to build more roads and highways, which of course only makes the problem worse. New roads generate higher levels of “induced traffic,” that is, new roads just invite drivers to drive more and lure people who take mass transit back to their cars. Eventually, we end up with more clogged roads rather than a long-term improvement in traffic flow.
    
    The coming decades will likely see more intense clustering of jobs, innovation, and productivity in a smaller number of bigger cities and city-regions. Some regions could end up bloated beyond the capacity of their infrastructure, while others struggle, their promise stymied by inadequate human or other resources.", mood: "stressed", food: "I didn't feel like eating much today after I got into that argument with Andrew... But I really should eat something since I'm so tired and stressed right now.", gratitude: "If I were to choose something I'm grateful for today, I would have to say that I'm grateful that Andrew sticks by me no matter what... I'm so lucky to have him by me.", title: "Argument with Andrew..." , date: "2021-06-11")
Entry.create(user_id: 1, the_entry: "In 1996, a loggerhead turtle called Adelita swam across 9,000 miles from Mexico to Japan, crossing the entire Pacific on her way. Wallace J. Nichols tracked this epic journey with a satellite tag. But Adelita herself had no such technology at her disposal. How did she steer a route across two oceans to find her destination?

    Nathan Putman has the answer. By testing hatchling turtles in a special tank, he has found that they can use the Earth’s magnetic field as their own Global Positioning System (GPS). By sensing the field, they can work out both their latitude and longitude and head in the right direction.
    
    Putman works in the lab of Ken Lohmann, who has been studying the magnetic abilities of loggerheads for over 20 years. In his lab at the University of North Carolina, Lohmann places hatchlings in a large water tank surrounded by a large grid of electromagnetic coils. In 1991, he found that the babies started in the opposite direction if he used the coils to reverse the direction of the magnetic field around them. They could use the field as a compass to get their bearing.
    
    Later, Lohmann showed that they can also use the magnetic field to work out their position. For them, this is literally a matter of life or death. Hatchlings born off the sea coast of Florida spend their early lives in the North Atlantic gyre, a warm current that circles between North America and Africa. If they’re swept towards the cold waters outside the gyre, they die. Their magnetic sense keeps them safe.
    
    Using his coil-surrounded tank, Lohmann could mimic the magnetic field at different parts of the Earth’s surface. If he simulated the field at the northern edge of the gyre, the hatchlings swam southwards. If he simulated the field at the gyre’s southern edge, the turtles swam west-northwest. These experiments showed that the turtles can use their magnetic sense to work out their latitude—their position on a north-south axis. Now, Putman has shown that they can also determine their longitude—their position on an east-west axis.", mood: "angry", food: "I'm two moods when I'm angry. I either eat a shit ton or I don't eat at all. And today was the latter. I haven't eaten much the past couple days I've noticed... I think I only ate a bowl of rice and some peaches today.", gratitude: "I'm grateful that my mom at least got some new groceries and that she did the laundry for us.", title: "An entire day of just stress and anger", date: "2021-06-12")
Entry.create(user_id: 2, the_entry: "He tweaked his magnetic tanks to simulate the fields in two positions with the same latitude at opposite ends of the Atlantic. If the field simulated the west Atlantic near Puerto Rico, the turtles swam northeast. If the field matched that on the east Atlantic near the Cape Verde Islands, the turtles swam southwest. In the wild, both headings would keep them within the safe, warm embrace of the North Atlantic gyre.

    Before now, we knew that several animal migrants, from loggerheads to reed warblers to sparrows, had some way of working out longitude, but no one knew how. By keeping the turtles in the same conditions, with only the magnetic fields around them changing, Putman clearly showed that they can use these fields to find their way. In the wild, they might well also use other landmarks like the position of the sea, sun and stars.
    
    Putman thinks that the turtles work out their position using two features of the Earth’s magnetic field that change over its surface. They can sense the field’s inclination, or the angle at which it dips towards the surface. At the poles, this angle is roughly 90 degrees and at the equator, it’s roughly zero degrees. They can also sense its intensity, which is strongest near the poles and weakest near the Equator. Different parts of the world have unique combinations of these two variables. Neither corresponds directly to either latitude or longitude, but together, they provide a “magnetic signature” that tells the turtle where it is.", mood: "sick", food: "I ate a lot of rice porridge today because I was sick.", gratitude: "I'm grateful that my mom came over from New Jersey to take care of me while I was sick.", date: "2021-06-10")
Entry.create(user_id: 2, the_entry: "Today, I am an inquisitor. An hyperbole would not be fictional and would not overstate the solemnness that I feel right now. My faith in the Constitution is whole; it is complete; it is total.  And I am not going to sit here and be an idle spectator to the diminution, the subversion, the destruction, of the Constitution.

    “Who can so properly be the inquisitors for the nation as the representatives of the nation themselves?” “The subjects of its jurisdiction are those offenses which proceed from the misconduct of public men.”* And that’s what we’re talking about. In other words, [the jurisdiction comes] from the abuse or violation of some public trust.
    
    It is wrong, I suggest, it is a misreading of the Constitution for any member here to assert that for a member to vote for an article of impeachment means that that member must be convinced that the President should be removed from office. The Constitution doesn’t say that. The powers relating to impeachment are an essential check in the hands of the body of the legislature against and upon the encroachments of the executive.The division between the two branches of the legislature, the House and the Senate, assigning to the one the right to accuse and to the other the right to judge—the framers of this Constitution were very astute. They did not make the accusers and the judges...the same person.
    
    We know the nature of impeachment. We’ve been talking about it a while now. It is chiefly designed for the President and his high ministers to somehow be called into account. It is designed to “bridle” the executive if he engages in excesses. “It is designed as a method of national inquest into the conduct of public men.”* The framers confided in the Congress the power, if need be, to remove the President in order to strike a delicate balance between a President swollen with power and grown tyrannical, and preservation of the independence of the executive.", mood: "happy", food: "Today I ate so much more than yesterday, after recovering. I ate my regular omelette this morning, but I also ate a bowl of rice with some dried seaweed. Then for lunch, I ate ramen. For dinner, I got some pho. Lots of noodles today actually.", gratitude: "I know I said this yesterday, but I'm very grateful for my mom who came to nurse me yesterday. Thanks to her I was able to get back on my feet. Hallelujah.", date: "2021-06-11")
Entry.create(user_id: 2, the_entry: "The nature of impeachment: a narrowly channeled exception to the separation of powers maxim. The Federal Convention of 1787 said that. It limited impeachment to high crimes and misdemeanors, and discounted and opposed the term “maladministration.” “It is to be used only for great misdemeanors,” so it was said in the North Carolina ratification convention. And in the Virginia ratification convention: “We do not trust our liberty to a particular branch. We need one branch to check the other.”

    ...The North Carolina ratification convention: “No one need be afraid that officers who commit oppression will pass with immunity.” “Prosecutions of impeachments will seldom fail to agitate the passions of the whole community,” said Hamilton in the Federalist Papers, number 65. “We divide into parties more or less friendly or inimical to the accused.”* I do not mean political parties in that sense.
    
    The drawing of political lines goes to the motivation behind impeachment; but impeachment must proceed within the confines of the constitutional term “high crime[s] and misdemeanors.” Of the impeachment process, it was Woodrow Wilson who said that “Nothing short of the grossest offenses against the plain law of the land will suffice to give them speed and effectiveness. Indignation so great as to overgrow party interest may secure a conviction; but nothing else can.”
    
    Common sense would be revolted if we engaged upon this process for petty reasons. Congress has a lot to do: appropriations, tax reform, health insurance, campaign finance reform, housing, environmental protection, energy sufficiency, mass transportation. Pettiness cannot be allowed to stand in the face of such overwhelming problems. So today we’re not being petty. We’re trying to be big, because the task we have before us is a big one.", mood: "meh", food: "Same omelette in the morning as usual, but because of clinic I skipped lunch and then for dinner I binge ate ramen and a bowl of rice with it.", gratitude: "I'm grateful for my family and my younger brother, who's sometimes annoying, but at least the apartment is livelier with him here.", title: "Oh I didn't know you could write a title here like this!", date: "2021-06-12")
Entry.create(user_id: 3, the_entry: "In 1894, British psychologist C. Lloyd Morgan published what’s called Morgan’s canon, the principle that suggestions of humanlike mental processes behind an animal’s behavior should be rejected if a simpler explanation will do.

    Still, people seem to maintain certain expectations, especially when it comes to birds and mammals. “We somehow want to prove they are as ‘smart’ as people,” zoologist Sara Shettleworth says. We want a bird that masters a vexing problem to be employing human-style insight.
    
    New Caledonian crows face the high end of these expectations, as possibly the second-best toolmakers on the planet.
    
    Their tools are hooked sticks or strips made from spike-edged leaves, and they use them in the wild to winkle grubs out of crevices. Researcher Russell Gray first saw the process on a cold morning in a mountain forest in New Caledonia, an island chain east of Australia. Over the course of days, he and crow researcher Gavin Hunt had gotten wild crows used to finding meat tidbits in holes in a log.Once the birds were checking the log reliably, the researchers placed a spiky tropical pandanus plant beside the log and hid behind a blind.", mood: "sad", food: "Since I'm on a diet I've only been eating grilled chicken breast every meal.", gratitude: "my girlfriend, taking all my jokes and understanding me even when things get tough.", date: "2021-06-10")
Entry.create(user_id: 3, the_entry: "A crow arrived. It hopped onto the pandanus plant, grabbed the spiked edge of one of the long straplike leaves and began a series of ripping motions. Instead of just tearing away one long strip, the bird ripped and nipped in a sequence to create a slanting stair-step edge on a leaf segment with a narrow point and a wide base. The process took only seconds. Then the bird dipped the narrow end of its leaf strip into a hole in the log, fished up the meat with the leaf-edge spikes, swallowed its prize and flew off.

    That was my ‘oh wow’ moment,” Gray says. After the crow had vanished, he picked up the tool the bird had left behind. “I had a go, and I couldn’t do it,” he recalls. Fishing the meat out was tricky. It turned out that Gray was moving the leaf shard too forcefully instead of gently stroking the spines against the treat.
    
    The crow’s deft physical manipulation was what inspired Gray and Auckland colleague Alex Taylor to test other wild crows to see if they employed the seemingly insightful string-pulling solutions that some ravens, kea parrots and other brainiac birds are known to employ. Three of four crows passed that test on the first try.", mood: "happy", food: "Chicken breasts", gratitude: "I'm grateful that Bitcoin finally went up.", title: "Bitcoin increased!", date: "2021-06-11")
Entry.create(user_id: 3, the_entry: "For one month after they left the nest, I led my four young ravens at least once and sometimes several times a day on thirty-minute walks. During these walks, I wrote down everything in their environment they pecked at. In the first sessions, I tried to be teacher. I touched specific objects—sticks, moss, rocks—and nothing that I touched remained untouched by them. They came to investigate what I had investigated, leading me to assume that young birds are aided in learning to identify food from the parents’ example. They also, however, contacted almost everything else that lay directly in their own paths. They soon became more independent by taking their own routes near mine. Even while walking along on their own, they pulled at leaves, grass stems, flowers, bark, pine needles, seeds, cones, clods of earth, and other objects they encountered. I wrote all this down, converting it to numbers. After they were thoroughly familiar with the background objects in these woods and started to ignore them, I seeded the path we would later walk together with objects they had never before encountered. Some of these were conspicuous food items: raspberries, dead meal worm beetles, and cooked corn kernels. Others were conspicuous and inedible: pebbles, glass chips, red winterberries. Still others were such highly cryptic foods as encased caddisfly larvae and moth cocoons. The results were dramatic.

    The four young birds on our daily walks contacted all new objects preferentially. They picked them out at a rate of up to tens of thousands of times greater than background or previously contacted objects. The main initial criterion for pecking or picking anything up was its novelty. In subsequent trials, when the previously novel items were edible, they became preferred and the inedible objects became “background” items, just like the leaves, grass, and pebbles, even if they were highly conspicuous. These experiments showed that ravens’ curiosity ensures exposure to all or almost all items in the environment.", mood: "angry", food: "Chicken breasts again", gratitude: "I'm grateful for nothing today. Bitcoin went down again and I'm angry.", title: "WTF Bitcoin DROPPED because of Elon Musk", date: "2021-06-12")
